// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmjgdymljufvayfvtwpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tamdkeW1sanVmdmF5ZnZ0d3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDc3NTcsImV4cCI6MjA2OTcyMzc1N30.p4j7bfBAv7Q3O-LwurDBCJLgh0FdWVkiJ1_Bh4_2FE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});